# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.button_album = QtWidgets.QPushButton(self.centralwidget)
        self.button_album.setMinimumSize(QtCore.QSize(130, 60))
        self.button_album.setAutoFillBackground(False)
        self.button_album.setIconSize(QtCore.QSize(40, 40))
        self.button_album.setObjectName("button_album")
        self.gridLayout_4.addWidget(self.button_album, 0, 5, 1, 1)
        self.button_cap = QtWidgets.QPushButton(self.centralwidget)
        self.button_cap.setMinimumSize(QtCore.QSize(130, 60))
        self.button_cap.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_cap.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.button_cap.setIconSize(QtCore.QSize(40, 40))
        self.button_cap.setObjectName("button_cap")
        self.gridLayout_4.addWidget(self.button_cap, 0, 3, 1, 1)
        self.button_open_camera = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_camera.setMinimumSize(QtCore.QSize(130, 60))
        self.button_open_camera.setIconSize(QtCore.QSize(40, 40))
        self.button_open_camera.setObjectName("button_open_camera")
        self.gridLayout_4.addWidget(self.button_open_camera, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_show_camera = QtWidgets.QLabel(self.widget)
        self.label_show_camera.setObjectName("label_show_camera")
        self.gridLayout_3.addWidget(self.label_show_camera, 0, 0, 1, 1)
        self.cap_label = QtWidgets.QLabel(self.widget)
        self.cap_label.setObjectName("cap_label")
        self.gridLayout_3.addWidget(self.cap_label, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_album.setText(_translate("MainWindow", "相册"))
        self.button_cap.setText(_translate("MainWindow", "拍照"))
        self.button_open_camera.setText(_translate("MainWindow", "打开相机"))
        self.label_show_camera.setText(_translate("MainWindow", "取景框"))
        self.cap_label.setText(_translate("MainWindow", "拍照浏览"))
